# Generated by Django 4.0.1 on 2022-01-22 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date',
        ),
        migrations.AddField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 5, 9, 43, 695682, tzinfo=utc)),
        ),
    ]
