# Generated by Django 4.0.1 on 2022-01-22 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comments_date_comments_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 5, 47, 32, 118193, tzinfo=utc)),
        ),
    ]
