# Generated by Django 4.0.1 on 2022-01-22 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comments_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 22, 5, 54, 38, 224049, tzinfo=utc)),
        ),
    ]
